# DEBUG - mode for advanced logging
logging:
  level:
    com.motosport.football: DEBUG

# Edit settings to access the database
database:
  host: localhost
  port: 5432
  username: postgres
  password: postgres